### PR TITLE
my profile ui

### PR DESCRIPTION
**Pull request by Addison1**
# Pull Request Template

## Description

first my profile ui

## Related Issue

Link to the issue here: #(issue)

## Type of Change

- [ ] Bug fix (fix)
- [V ] New feature (feat)

## Checklist

- [V] Code follows project guidelines
- [ ] Self-reviewed code

## Additional Notes

Any additional information.

## Reviewers

xue

### CODE REVIEW

**Comment by xuelink** [comment]
@Addison1 can you please fix `flutter analyze` issue ? 

```
Run flutter analyze
Analyzing langx-flutter...                                      

   info • The file name 'Shield_svg.dart' isn't a lower_case_with_underscores identifier • lib/components/Shield_svg.dart:1:1 • file_names
   info • Unnecessary 'const' keyword • lib/components/profile_study_languages_card.dart:31:19 • unnecessary_const

2 issues found. (ran in 9.7s)
Error: Process completed with exit code 1.
```

**Comment by xuelink** [comment]
image

love your work

**Comment by xuelink** [comment]
Before merge this PR, can you please fix for the dark mode UI @Addison1 


https://github.com/langx/langx-flutter/assets/3280475/36101660-f416-42ba-862b-5f3277938305

**Review by xuelink — CHANGES_REQUESTED** [review]
For the dark mode can you pls use dark template that @DH-555 already wrote `theme.dart` here.  I think it can be useful for you

**Comment by DH-555** [comment]
I think it's used automatically?

**Comment by DH-555** [comment]
Oh, I think that the theme is what needs the change. Let's merge this

**Comment by xuelink** [comment]
> I think it's used automatically?

Nope,i added and removed. PR wont close this issue, only it will do checked in checklist in the first post here now.

**Comment by xuelink** [comment]
```
To inspect this widget in Flutter DevTools, visit:
http://127.0.0.1:9101/#/inspector?uri=http%3A%2F%2F127.0.0.1%3A49671%2FBkvcLigkMlc%3D%2F&inspectorRef=inspector-0

The overflowing RenderFlex has an orientation of Axis.vertical.
The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and
black striped pattern. This is usually caused by the contents being too big for the RenderFlex.
Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the
RenderFlex to fit within the available space instead of being sized to their natural size.
This is considered an error condition because it indicates that there is content that cannot be
seen. If the content is legitimately bigger than the available space, consider clipping it with a
ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex,
like a ListView.
The specific RenderFlex in question is: RenderFlex#a6186 OVERFLOWING:
  creator: Column ← Padding ← Semantics ← DefaultTextStyle ← AnimatedDefaultTextStyle ←
    _InkFeatures-[GlobalKey#f9d5d ink renderer] ← NotificationListener<LayoutChangedNotification> ←
    CustomPaint ← _ShapeBorderPaint ← PhysicalShape ← _MaterialInterior ← Material ← ⋯
  parentData: offset=Offset(16.0, 16.0) (can use size)
  constraints: BoxConstraints(w=315.0, h=510.0)
  size: Size(315.0, 510.0)
  direction: vertical
  mainAxisAlignment: start
  mainAxisSize: max
  crossAxisAlignment: center
  verticalDirection: down
◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤
════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: A RenderFlex overflowed by 5.0 pixels on the bottom.
```

> Oh, I think that the theme is what needs the change. Let's merge this

At least, we can fix that one here before merging.

**Comment by xuelink** [comment]
@DH-555 If you update `theme.dart` within this PR, gonna be awesome as well!

**Comment by DH-555** [comment]
🆗

**Comment by xuelink** [comment]
Ok, guys, im going to merge this repo for further, we can open new PR's spesifically additions for dark theme and other issues for sure!

**Review by xuelink — APPROVED** [review]

**Pull request merged**
